In [57]:
import tensorflow as tf

In [58]:
from tensorflow import keras

In [59]:
from tensorflow.keras import layers

In [60]:
import pandas as pd

In [61]:
import numpy as np

In [62]:
data=pd.read_csv("C:/Users/satheesh/Downloads/Names1/Names.csv")

In [63]:
data.head()

Id       Name  Year Gender  Count
0   1       Mary  1880      F   7065
1   2       Anna  1880      F   2604
2   3       Emma  1880      F   2003
3   4  Elizabeth  1880      F   1939
4   5     Minnie  1880      F   1746

In [64]:
df1=data.drop(["Id","Year","Count"],axis=1)

In [65]:
df1.head()

Name Gender
0       Mary      F
1       Anna      F
2       Emma      F
3  Elizabeth      F
4     Minnie      F

In [66]:
df1.shape

(1825433, 2)

In [67]:
df1["Name"].unique()

array(['Mary', 'Anna', 'Emma', ..., 'Zijun', 'Zilas', 'Zirui'],
      dtype=object)

In [68]:
df1["Name"].unique().size

93889

In [69]:
df1["Name"].nunique()

93889

In [70]:
df1["Name"].value_counts()

William        270
Jessie         270
Jesse          270
Leslie         270
Sidney         270
              ... 
Jeanjacques      1
Yasmeli          1
Voight           1
Gwennetta        1
Dametrious       1
Name: Name, Length: 93889, dtype: int64

In [71]:
df1["Gender"].astype("category").cat.codes#we can use here getdummies but this is new way

0          0
1          0
2          0
3          0
4          0
          ..
1825428    1
1825429    1
1825430    1
1825431    1
1825432    1
Length: 1825433, dtype: int8

In [72]:
df1["Gender"]=df1["Gender"].astype("category").cat.codes

In [73]:
df1.head()

Name  Gender
0       Mary       0
1       Anna       0
2       Emma       0
3  Elizabeth       0
4     Minnie       0

In [74]:
gd1=df1.groupby("Name")

In [75]:
df2=gd1.mean()

In [76]:
df2.head()

Gender
Name             
Aaban         1.0
Aabha         0.0
Aabid         1.0
Aabriella     0.0
Aadam         1.0

In [77]:
df2.reset_index(inplace=True)

In [78]:
df2.head()

Name  Gender
0      Aaban     1.0
1      Aabha     0.0
2      Aabid     1.0
3  Aabriella     0.0
4      Aadam     1.0

In [79]:
df2["Gender"]=df2["Gender"].astype("int")

In [80]:
df2.head()

Name  Gender
0      Aaban       1
1      Aabha       0
2      Aabid       1
3  Aabriella       0
4      Aadam       1

In [81]:
import string

In [82]:
letters=list(string.ascii_lowercase)

In [83]:
list(range(1,27))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26]

In [84]:
vocab=dict(zip(letters,range(1,27)))

In [85]:
vocab

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26}

In [86]:
vocab["n"]

14

In [87]:
df2["Name"][0]

'Aaban'

In [88]:
n=[]
for i in df2["Name"][5]:
  num=vocab[i.lower()]
  n.append(num)
  
print(df2["Name"][5])
print(n) 


Aadan
[1, 1, 4, 1, 14]


In [89]:
df2.shape

(93889, 2)

In [90]:
df2.shape[0]

93889

In [91]:
for i in range(1,10):
  print(df2["Name"][i])

Aabha
Aabid
Aabriella
Aadam
Aadan
Aadarsh
Aaden
Aadesh
Aadhav


In [92]:
df2

Name  Gender
0          Aaban       1
1          Aabha       0
2          Aabid       1
3      Aabriella       0
4          Aadam       1
...          ...     ...
93884  Zytavious       1
93885     Zyvion       1
93886    Zyyanna       0
93887      Zyyon       1
93888      Zzyzx       1

[93889 rows x 2 columns]

In [93]:
def name_to_num():
  for i in range(0,df2.shape[0]):
    seq=[vocab[j.lower()]    for j in df2["Name"][i]]
    df2["Name"][i]=seq

In [94]:
import warnings

In [95]:
warnings.filterwarnings("ignore")

In [96]:
name_to_num()

In [97]:
df2.head()

Name  Gender
0                [1, 1, 2, 1, 14]       1
1                 [1, 1, 2, 8, 1]       0
2                 [1, 1, 2, 9, 4]       1
3  [1, 1, 2, 18, 9, 5, 12, 12, 1]       0
4                [1, 1, 4, 1, 13]       1

In [98]:
X=df2["Name"].values

In [99]:
y=df2["Gender"].values

In [100]:
X

array([list([1, 1, 2, 1, 14]), list([1, 1, 2, 8, 1]),
       list([1, 1, 2, 9, 4]), ..., list([26, 25, 25, 1, 14, 14, 1]),
       list([26, 25, 25, 15, 14]), list([26, 26, 25, 26, 24])],
      dtype=object)

In [101]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [102]:
x=pad_sequences(df2["Name"].values,maxlen=10,padding="pre")

In [103]:
x

array([[ 0,  0,  0, ...,  2,  1, 14],
       [ 0,  0,  0, ...,  2,  8,  1],
       [ 0,  0,  0, ...,  2,  9,  4],
       ...,
       [ 0,  0,  0, ..., 14, 14,  1],
       [ 0,  0,  0, ..., 25, 15, 14],
       [ 0,  0,  0, ..., 25, 26, 24]])

In [104]:
X[0]

[1, 1, 2, 1, 14]

In [105]:
x[0]

array([ 0,  0,  0,  0,  0,  1,  1,  2,  1, 14])

# model_building

In [106]:
inp=layers.Input(shape=(10,))

In [107]:
emb=layers.Embedding(input_dim=27,output_dim=5)(inp)

In [108]:
lstm1=layers.LSTM(units=32,return_sequences=True)(emb)

In [109]:
lstm2=layers.LSTM(units=64)(lstm1)

In [110]:
out=layers.Dense(units=1,activation="sigmoid")(lstm2)

In [111]:
model=keras.Model(inputs=inp,outputs=out)

In [112]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10)]              0         
_________________________________________________________________
embedding (Embedding)        (None, 10, 5)             135       
_________________________________________________________________
lstm (LSTM)                  (None, 10, 32)            4864      
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                24832     
_________________________________________________________________
dense (Dense)                (None, 1)                 65        
Total params: 29,896
Trainable params: 29,896
Non-trainable params: 0
_________________________________________________________________


In [113]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [114]:
model.fit(x,y,epochs=25,batch_size=256,validation_split=0.20)

Epoch 1/25
294/294 [==============================] - 14s 32ms/step - loss: 0.5626 - accuracy: 0.7130 - val_loss: 0.4183 - val_accuracy: 0.8076
Epoch 2/25
294/294 [==============================] - 8s 27ms/step - loss: 0.4033 - accuracy: 0.8120 - val_loss: 0.3892 - val_accuracy: 0.8221
Epoch 3/25
294/294 [==============================] - 9s 29ms/step - loss: 0.3931 - accuracy: 0.8154 - val_loss: 0.3858 - val_accuracy: 0.8225
Epoch 4/25
294/294 [==============================] - 8s 28ms/step - loss: 0.3895 - accuracy: 0.8179 - val_loss: 0.3867 - val_accuracy: 0.8200
Epoch 5/25
294/294 [==============================] - 9s 29ms/step - loss: 0.3864 - accuracy: 0.8179 - val_loss: 0.3821 - val_accuracy: 0.8240
Epoch 6/25
294/294 [==============================] - 8s 28ms/step - loss: 0.3834 - accuracy: 0.8202 - val_loss: 0.3813 - val_accuracy: 0.8262
Epoch 7/25
294/294 [==============================] - 8s 29ms/step - loss: 0.3798 - accuracy: 0.8229 - val_loss: 0.3796 - val_accuracy: 0.826

In [115]:
name="john"

In [116]:
s=[vocab[i.lower()] for i in name]
print(s)

[10, 15, 8, 14]


In [117]:
test=pad_sequences([s],maxlen=10)

In [118]:
test

array([[ 0,  0,  0,  0,  0,  0, 10, 15,  8, 14]])

In [119]:
p=model.predict(test)

In [120]:
if p>=0.5:
  print(name,"is male")
else :
  print(name,"is female")

john is male
